// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packageFormat.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "packageFormat.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace udpStream {

namespace {

const ::google::protobuf::Descriptor* updBytes_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  updBytes_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_packageFormat_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_packageFormat_2eproto() {
  protobuf_AddDesc_packageFormat_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "packageFormat.proto");
  GOOGLE_CHECK(file != NULL);
  updBytes_descriptor_ = file->message_type(0);
  static const int updBytes_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(updBytes, packid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(updBytes, pack_),
  };
  updBytes_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      updBytes_descriptor_,
      updBytes::internal_default_instance(),
      updBytes_offsets_,
      -1,
      -1,
      -1,
      sizeof(updBytes),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(updBytes, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_packageFormat_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      updBytes_descriptor_, updBytes::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_packageFormat_2eproto() {
  updBytes_default_instance_.Shutdown();
  delete updBytes_reflection_;
}

void protobuf_InitDefaults_packageFormat_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  updBytes_default_instance_.DefaultConstruct();
  updBytes_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_packageFormat_2eproto_once_);
void protobuf_InitDefaults_packageFormat_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_packageFormat_2eproto_once_,
                 &protobuf_InitDefaults_packageFormat_2eproto_impl);
}
void protobuf_AddDesc_packageFormat_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_packageFormat_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023packageFormat.proto\022\tudpStream\"(\n\010updB"
    "ytes\022\016\n\006packId\030\001 \001(\r\022\014\n\004pack\030\002 \001(\014b\006prot"
    "o3", 82);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "packageFormat.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_packageFormat_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_packageFormat_2eproto_once_);
void protobuf_AddDesc_packageFormat_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_packageFormat_2eproto_once_,
                 &protobuf_AddDesc_packageFormat_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_packageFormat_2eproto {
  StaticDescriptorInitializer_packageFormat_2eproto() {
    protobuf_AddDesc_packageFormat_2eproto();
  }
} static_descriptor_initializer_packageFormat_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int updBytes::kPackIdFieldNumber;
const int updBytes::kPackFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

updBytes::updBytes()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_packageFormat_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:udpStream.updBytes)
}

void updBytes::InitAsDefaultInstance() {
}

updBytes::updBytes(const updBytes& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:udpStream.updBytes)
}

void updBytes::SharedCtor() {
  pack_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  packid_ = 0u;
  _cached_size_ = 0;
}

updBytes::~updBytes() {
  // @@protoc_insertion_point(destructor:udpStream.updBytes)
  SharedDtor();
}

void updBytes::SharedDtor() {
  pack_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void updBytes::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* updBytes::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return updBytes_descriptor_;
}

const updBytes& updBytes::default_instance() {
  protobuf_InitDefaults_packageFormat_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<updBytes> updBytes_default_instance_;

updBytes* updBytes::New(::google::protobuf::Arena* arena) const {
  updBytes* n = new updBytes;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void updBytes::Clear() {
// @@protoc_insertion_point(message_clear_start:udpStream.updBytes)
  packid_ = 0u;
  pack_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool updBytes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:udpStream.updBytes)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 packId = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &packid_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_pack;
        break;
      }

      // optional bytes pack = 2;
      case 2: {
        if (tag == 18) {
         parse_pack:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_pack()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:udpStream.updBytes)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:udpStream.updBytes)
  return false;
#undef DO_
}

void updBytes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:udpStream.updBytes)
  // optional uint32 packId = 1;
  if (this->packid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->packid(), output);
  }

  // optional bytes pack = 2;
  if (this->pack().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->pack(), output);
  }

  // @@protoc_insertion_point(serialize_end:udpStream.updBytes)
}

::google::protobuf::uint8* updBytes::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:udpStream.updBytes)
  // optional uint32 packId = 1;
  if (this->packid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->packid(), target);
  }

  // optional bytes pack = 2;
  if (this->pack().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->pack(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:udpStream.updBytes)
  return target;
}

size_t updBytes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:udpStream.updBytes)
  size_t total_size = 0;

  // optional uint32 packId = 1;
  if (this->packid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->packid());
  }

  // optional bytes pack = 2;
  if (this->pack().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->pack());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void updBytes::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:udpStream.updBytes)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const updBytes* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const updBytes>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:udpStream.updBytes)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:udpStream.updBytes)
    UnsafeMergeFrom(*source);
  }
}

void updBytes::MergeFrom(const updBytes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:udpStream.updBytes)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void updBytes::UnsafeMergeFrom(const updBytes& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.packid() != 0) {
    set_packid(from.packid());
  }
  if (from.pack().size() > 0) {

    pack_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pack_);
  }
}

void updBytes::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:udpStream.updBytes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void updBytes::CopyFrom(const updBytes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:udpStream.updBytes)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool updBytes::IsInitialized() const {

  return true;
}

void updBytes::Swap(updBytes* other) {
  if (other == this) return;
  InternalSwap(other);
}
void updBytes::InternalSwap(updBytes* other) {
  std::swap(packid_, other->packid_);
  pack_.Swap(&other->pack_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata updBytes::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = updBytes_descriptor_;
  metadata.reflection = updBytes_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// updBytes

// optional uint32 packId = 1;
void updBytes::clear_packid() {
  packid_ = 0u;
}
::google::protobuf::uint32 updBytes::packid() const {
  // @@protoc_insertion_point(field_get:udpStream.updBytes.packId)
  return packid_;
}
void updBytes::set_packid(::google::protobuf::uint32 value) {
  
  packid_ = value;
  // @@protoc_insertion_point(field_set:udpStream.updBytes.packId)
}

// optional bytes pack = 2;
void updBytes::clear_pack() {
  pack_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& updBytes::pack() const {
  // @@protoc_insertion_point(field_get:udpStream.updBytes.pack)
  return pack_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void updBytes::set_pack(const ::std::string& value) {
  
  pack_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:udpStream.updBytes.pack)
}
void updBytes::set_pack(const char* value) {
  
  pack_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:udpStream.updBytes.pack)
}
void updBytes::set_pack(const void* value, size_t size) {
  
  pack_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:udpStream.updBytes.pack)
}
::std::string* updBytes::mutable_pack() {
  
  // @@protoc_insertion_point(field_mutable:udpStream.updBytes.pack)
  return pack_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* updBytes::release_pack() {
  // @@protoc_insertion_point(field_release:udpStream.updBytes.pack)
  
  return pack_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void updBytes::set_allocated_pack(::std::string* pack) {
  if (pack != NULL) {
    
  } else {
    
  }
  pack_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pack);
  // @@protoc_insertion_point(field_set_allocated:udpStream.updBytes.pack)
}

inline const updBytes* updBytes::internal_default_instance() {
  return &updBytes_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace udpStream

// @@protoc_insertion_point(global_scope)
